apiVersion: v1
kind: PersistentVolumeClaim  # request for a storage resource by a user
metadata:
  name: local-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # FIXME: required by test but not actually possible?
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume  # abstract storage resource
metadata:
  name: local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  # mounted by one node at a time
  hostPath:  # we use an underlying node to simulate a network file system
    # path: "/mnt/data"
    path: "/home/data"
---
# a fix for not being able to use /mnt/data directory with GKE
# https://discuss.kubernetes.io/t/running-tutorial-mysql-example-gives-me-read-only-file-system-error/3197/7
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: manual
# provisioner: kubernetes.io/gce-pd  # Google Cloud Engine-managed storage
# parameters:
#   type: pd-standard
#   replication-type: none
