version: "3"

services:
  poll:
    build: "./poll"
    # also specifying image causes Connection Refused error
    # between Python and Redis
    # image: dop-poll:latest
    depends_on:
      - redis
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=$REDIS_HOST
    networks:
      - poll-tier
    restart: on-failure

  worker:
    build: "./worker"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=$REDIS_HOST
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    networks:
      - back-tier
    restart: always

  result:
    build: "./result"
    depends_on:
      - db
    environment:
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - "5001:80"
    networks:
      - result-tier
    restart: on-failure
    # we need to limit memory for this leaky container
    # mem_limit: 100m

  redis:
    image: redis
    environment:
      - REDIS=""
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier
    restart: always

  db:
    image: postgres
    environment:
      - DB=""
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - back-tier
      - result-tier
    restart: always

volumes:
  db-data:

networks:
  poll-tier:
  back-tier:
  result-tier: